# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d2561e08e8b6c32100c29e945cf181707e7bd05933a498721ab0e536cec92a0d492356d7f742904d1ea730e4431da111da12083cfcf799a90c1a0f74c0c0568

test:
  secret_key_base: 18ad73e6a5e8ddb75a63acc3840129b35540f01c6e63757f213535c8151dcd15abcdced7cc77ceaee6f9f206a7cf64b958f688eee0592eabe9533230815f6304

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
